services:
  server:
    build:
      context: .
    container_name: bcool-be
    restart: always
    env_file:
      - .env
    ports:
      - "8998:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: bcool-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: bcool-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"

volumes:
  postgres_data: